# -*- coding: utf-8 -*-
"""Long-form write-ups (3-5 sentences) for every name in the ranked 50.

company_notes.py carries two-sentence notes sized for the ranking report. The
operator asked for 3-5 sentences per name in the emailed list, covering BOTH
why the company is on the list and what its actual AI capability is -- so these
are written to a fixed shape rather than free-form:

  1. What the company does, plainly.
  2. The NAMED AI product or model doing the work (the operator's own test:
     AI DJ, AI-generated police reports, AI-powered PT -- a named product at a
     price, not a capability slide).
  3. The delete-the-model verdict: does the product still exist and sell?
  4. The counter-argument, the risk, or what would falsify it.

Where a name's honest verdict is "AI is real but not load-bearing", say so in
the write-up. The list is a ranking, not a recommendation, and the bottom of it
should read that way.
"""

LONG = {

# ---------------------------------------------------------------- tier 1
"HNGE": "Hinge Health delivers musculoskeletal physical therapy remotely to employer and health-plan members, competing against in-person PT clinics. Its computer-vision engine, marketed as TrueMotion, uses the phone camera to track joint angle and rep quality in real time and correct form without a human in the loop, which is the specific labour the model is replacing. Delete the model and there is no product: what remains is a video library plus a call centre, which is not what employers are buying or what supports the pricing. The risk is not capability but competition and contracting -- this is a crowded category selling into benefits managers, and retention through a full plan year is the number that matters.",

"GH": "Guardant Health sells blood-based cancer tests, principally Guardant360 for therapy selection in advanced disease and Shield for colorectal cancer screening. The screening and tumour-naive products are the AI-central ones: with no tissue biopsy to anchor on, the test must infer cancer from methylation patterns and cell-free DNA fragmentomics, and that inference is a trained classifier rather than a lookup. Delete the model and Shield does not exist at all, which is precisely the distinction that separates Guardant from tumour-informed competitors that track already-known variants. It sits at the top of this list because the model is the product AND the moat is unbuyable -- FDA clearance plus reimbursement is not something a frontier lab acquires by writing a cheque.",

"IRTC": "iRhythm makes the Zio patch, a wearable cardiac monitor worn for up to 14 days, sold to cardiologists and reimbursed under its own CPT codes. Fourteen days of continuous ECG is far too much signal for a human to read, so a deep-learning classifier does the first pass on every beat and surfaces only the arrhythmias, with technicians reviewing the model's output rather than the raw trace. Delete the model and there is no report to deliver and therefore nothing to bill -- the economics of the product depend on the classifier existing. As with Guardant, the defensibility is regulatory and reimbursement-based rather than technical, which is the strongest form of protection available on this list.",

"APP": "AppLovin operates a mobile advertising exchange, matching ad inventory to users in a real-time auction. Its AXON model is not a feature of the business, it IS the business: the ranking and bidding model decides what to show and at what price on every impression, and the step-change in AppLovin's margins tracked the AXON 2.0 rollout rather than any change in inventory or sales headcount. Delete the model and the exchange still technically clears, but it clears at commodity economics -- the entire spread over competitors is model quality. The counter-argument is concentration and disclosure: this is a company whose P&L is a single model's performance, which is a real risk as well as the thesis.",

"RDNT": "RadNet is the largest independent operator of outpatient diagnostic imaging centres in the US, and separately builds AI through its DeepHealth subsidiary. The combination is the point: it owns the scans, the radiologists and the patient relationship, so its breast-screening AI is sold as a cash-pay upsell directly to the patient at the point of care rather than negotiated into a hospital IT budget. Delete the model and the imaging business survives intact, so centrality is 4 rather than 5 -- but the AI is a genuine incremental revenue line, not a cost story. It also runs a real label flywheel, since its own radiologists generate the ground truth that trains the next model version.",

"HTFL": "HeartFlow takes an ordinary coronary CT scan and computes fractional flow reserve non-invasively, telling a cardiologist whether a blockage is actually restricting blood flow. The entire product is an inference on an image: there is no hardware, no consumable and no procedure, and the company is paid per analysis under its own reimbursement pathway. Delete the model and literally nothing remains -- this is the purest archetype-A name in the whole universe, which is why it scores at the top on centrality. What it lacks is scale and independent commercial proof relative to the diagnostics names above it, and adoption depends on cardiologists changing referral habits.",

"AXON": "Axon sells Tasers, body cameras and the Evidence.com digital evidence platform to police departments, which makes it the system of record for American law enforcement video. Draft One is the named product that matters here: it turns body-camera audio into a first-draft police report, attacking officer paperwork hours rather than selling another camera. Delete the model and Axon is still an excellent business, so it is archetype B -- but it is the best example on this list of a corpus company converting to model-native, because nobody else has the video, the chain-of-custody and the procurement relationships. Evidentiary standards and government procurement are exactly the kind of moat a frontier lab cannot buy.",

"DE": "Deere sells agricultural equipment and, increasingly, the software that decides what the equipment does in the field. See & Spray is the named product: cameras and on-board inference identify individual plants and actuate nozzles per plant, cutting herbicide volume materially, and Deere prices it on the outcome rather than as a hardware option. Delete the model and you have a conventional sprayer -- the machine still sells, so centrality is 4, but the specific product and its pricing disappear. The moat is the physical fleet and the agronomic data it collects, which is a data-collection channel a software company cannot replicate.",

"UPST": "Upstart is a consumer lending platform whose entire proposition is that its underwriting model approves borrowers a FICO cut-off would reject, at equivalent or better loss rates. The credit decision IS the model -- there is no separate product, and the company's disclosed AI-revenue language is among the rarest in the filing screen. Delete the model and Upstart is an origination front-end with no reason to exist, which makes it unambiguously archetype A. The honest caveat is that this is a balance-sheet-and-funding-market story as much as a model story: the model's quality is only observable through a full credit cycle, and it has not yet been through a severe one.",

"IOT": "Samsara sells a connected-operations platform to commercial fleets -- trucking, construction, utilities -- centred on an AI dash cam. The camera runs computer vision on-device to make the safety determination in the moment (distraction, tailgating, rolling stops) rather than shipping video to a human reviewer, which is what makes the product a coaching tool instead of a recording tool. Delete the model and you sell a dashcam and a GPS tracker into a commoditised market at a fraction of the price. The reason it ranks here rather than lower is that the training fleet is customer-funded: every camera a customer pays for improves the model, which is the same shape as Tesla's fleet advantage without the capital intensity.",

"RXRX": "Recursion runs an automated biology lab that images millions of cell cultures and uses learned representations to map how compounds perturb cells, aiming to industrialise drug discovery. The company is functionally a model with a wet lab attached -- it clears the AI-revenue and AI-officer filing screens more strongly than almost anything else in the universe. Delete the model and there is no discovery engine, only a very expensive imaging facility. It ranks below the diagnostics names for one reason: output. The platform's promise is enormous and unproven, and the honest description is a high-variance option on a scientific bet, not a business with demonstrated model-driven revenue.",

"PLTR": "Palantir builds Foundry and AIP, platforms that integrate messy enterprise and government data into a queryable model of how an organisation actually works. The scarce asset is the ontology -- the mapping from raw systems to the entities and actions a business cares about -- and that is precisely what an LLM needs in order to ACT rather than merely answer, which is why very few companies have solved it. Delete the model and Palantir is still a formidable data-integration business, so this is archetype B, but the ontology makes it the most credible path from corpus to agent on this list. The counter-argument is valuation and the persistent difficulty of separating software revenue from what is effectively forward-deployed consulting.",

"CRWD": "CrowdStrike sells endpoint security through the Falcon platform, with Charlotte AI as the named agentic layer that triages alerts. The structural insight is the label flywheel: its OverWatch managed-hunting service is staffed by human experts who label every real intrusion they find, and those labels train the detection models -- so the services line is a labelling operation disguised as a cost centre. What makes this credible rather than a story is that OverWatch sits in COGS at roughly 75% gross margin and margin still expands, meaning the flywheel pays for itself. Two marks against: the CTO departed in 2026, which is worth watching against the detection-engineering bench, and centrality is only 3 -- delete the models and Falcon is still a signature-and-telemetry product that sells.",

"KDK": "Kodiak Robotics operates driverless trucks on long-haul freight lanes, with the Kodiak Driver as the product it intends to sell or operate. The driving policy is the entire company: there is no other revenue line, no hardware franchise and no services business to fall back on. Delete the model and nothing remains, so centrality is a clean 5. It ranks in the middle rather than the top because product maturity is 1 -- the honest state is pre-scale commercial deployment, and the gap between a working demonstration and a priced, insured, at-scale freight operation is where most autonomy companies have historically died.",

"NTRA": "Natera sells molecular diagnostics, principally Signatera for detecting residual cancer after treatment and Panorama in prenatal screening. It is on this list because it is an outstanding business with a genuine data asset, but I want to be precise about the AI: Signatera is tumour-informed, meaning it sequences the patient's tumour first and then tracks those already-known variants in blood. That is careful, high-quality statistics and assay engineering -- it is not a learned model making the call, which is why ml_content scores 1 and why Guardant's tumour-naive products rank above it. Delete the model and the test still works, because the discriminating step is knowing which variants to look for, not inferring them.",

"SERV": "Serve Robotics operates autonomous sidewalk delivery robots, principally for restaurant delivery in dense urban markets. Like Kodiak and Aurora it is pure autonomy -- the navigation policy is the only product, so deleting the model leaves nothing behind. It ranks here rather than higher purely on scale: at roughly $569m of market value this is a sub-scale company where execution risk and financing risk dominate the thesis. The strategic question is whether sidewalk delivery is a defensible market or a feature that a larger logistics or delivery platform absorbs once the technology is proven.",

"TSLA": "Tesla sells electric vehicles and, through Full Self-Driving, an autonomy software product priced as a premium on top of the car. The structural advantage is that the training fleet is not a cost -- customers pay for the vehicles that collect the driving data, which inverts the economics every other autonomy company faces. Delete the model and Tesla is still a large and profitable car company, so centrality is 4 rather than 5, but FSD is the highest-margin revenue in the business and the entire robotaxi thesis rests on it. The counter-argument is that the camera-only approach remains unproven at the reliability level regulators will require, and the timeline has slipped repeatedly.",

"AUR": "Aurora Innovation develops the Aurora Driver for autonomous long-haul trucking, operating on Texas freight lanes. The driving policy is the whole product, exactly as with Kodiak, and the company is pre-revenue in any meaningful commercial sense. It moved DOWN four places this month on a specific signal: co-founder and Chief Product Officer Sterling Anderson resigned in May 2025 from both the role and the board, which for a pre-revenue company whose entire thesis is forward execution is the technical-leadership criterion breaking rather than a footnote. The scoring penalty is deliberately flat and understates it -- read the event, not the four places.",

"EVLV": "Evolv Technologies sells AI-based weapons-detection screening to schools, stadiums and hospitals, positioned as a faster alternative to metal detectors. It is genuinely model-native -- the discrimination between a firearm and a laptop is a learned classifier, and deleting it leaves a walk-through frame with no capability. It carries an explicit credibility discount in the ranking, and that is the point of including it: the company reached an FTC settlement over its detection-efficacy claims, and independent testing found knives passing through. This is the cleanest example on the list of why 'model-native' and 'good investment' are separate questions -- the architecture is right and the evidence of efficacy is contested.",

"NET": "Cloudflare runs a global edge network and has built Workers AI, which puts inference on servers physically close to users rather than in a central datacentre. The developer traction is real and measurable -- it has the deepest MCP repository traction of any filer I screened, at over 5,700 GitHub stars, and its engineering blog writes in operator register rather than marketing register. Delete the models and Cloudflare is still a large CDN and security business, so centrality is 3. The specific thing I would watch is the GPU-utilisation claim: gross margin fell from 77.8% to 71.8% while capex intensity dropped from 19% to 9% of revenue, which is the signature of capacity deployed but not yet utilised, so a gross-margin inflection is the falsifiable test of whether the efficiency story is true.",

# ---------------------------------------------------------------- tier 2
"GEHC": "GE HealthCare manufactures imaging hardware -- CT, MRI, ultrasound -- and has the largest installed base of FDA-cleared imaging AI algorithms in the world. The AI is embedded in the scanner: reconstruction, dose reduction, and automated measurement run on the device, so the capability ships with equipment hospitals are already buying. Delete the models and the scanners still sell, which caps centrality at 3, but the installed base is a distribution advantage no software-only entrant can match. It also named a senior AI officer, and the open question is monetisation -- whether embedded AI stays a feature that helps win hardware deals or becomes a separately-priced line.",

"TEM": "Tempus AI sequences tumours and links the molecular result to the patient's real-world clinical outcome, building a dataset that connects genomics to what actually happened to the patient. That linkage is the scarce asset -- sequencing is increasingly commoditised, but the clinical-molecular join is very hard to assemble and is what pharmaceutical companies pay for. Delete the model and the sequencing business remains, so this is archetype B with a strong label flywheel. The diligence question is revenue mix: the data-licensing revenue is the high-quality part of the story and the ratio of licensing to lower-margin lab work is what determines whether this is a data company or a lab company.",

"ADPT": "Adaptive Biotechnologies reads the immune system's receptor repertoire, commercially through clonoSEQ for tracking minimal residual disease in blood cancers. I want to split the product from the promise: clonoSEQ works by counting a clone that has already been identified, which is excellent assay engineering rather than a learned model doing the discriminating work. The genuinely ambitious ML is the TCR-antigen map -- learning which immune receptors bind which targets, which would be a foundational biological asset -- and that remains unproven commercially. So the score reflects a real business plus a large unrealised option, not a model that is currently central to revenue.",

"CNH": "CNH Industrial makes agricultural and construction equipment -- Case IH and New Holland -- and is Deere's most direct competitor in autonomous agriculture. It is on this list because of a method finding rather than a hunch: it was invisible to every prior screen because my phrase set was tuned to software vocabulary, and only appeared once I screened in industrial dialect for terms like sensor fusion, perception stack and autonomous navigation. Its capability is the same class as Deere's -- per-plant computer vision driving targeted application, plus autonomy features on the machine itself. It ranks a tier below Deere because the installed fleet collecting training data is smaller, and in this category the data-collection channel is the moat.",

"AVAV": "AeroVironment makes small unmanned aircraft and loitering munitions -- Switchblade being the best known -- sold principally to defence customers. The AI is autonomy and target recognition running on the vehicle, which must work without a network connection in a contested environment. What makes defence structurally interesting here is a point that generalises: the defence buyer explicitly accepts consequence-of-error in a way healthcare and automotive regulators never will, which removes the timeline constraint that holds back most physical-AI deployment. Delete the model and the airframes still sell, so centrality is 3, but government procurement is among the least encroachable positions on this list.",

"ONDS": "Ondas Holdings builds autonomous drone systems and private wireless networks, serving defence, rail and critical-infrastructure customers. It is genuinely autonomy-first rather than a hardware company with an AI slide -- the drones conduct inspection and security missions without an operator flying them, which is the product being bought. Delete the model and the value proposition collapses back into manned inspection. The caveat is scale: at roughly $4.4bn it is far smaller and more financing-dependent than the defence primes, and the ranking reflects capability rather than any view that the position is de-risked.",

"RELX": "RELX owns LexisNexis in legal and Elsevier in scientific publishing, which means it owns the ground truth in two domains where being right is the entire product. Lexis+ AI is the named product: it answers legal research questions with citations into a corpus it controls, so it can sell the answer rather than the search. Delete the model and the subscription business is intact, so this is archetype B with an unusually strong corpus. It carries the highest lab-encroachment risk on the list at 3/3, and this is the one I would push back on my own inclusion of: the workflow is text-in, text-out over a licensable corpus, and private competitors like Harvey plus frontier labs moving up the stack are attacking exactly this. Your instinct not to trust that position over time is the right one.",

"TRI": "Thomson Reuters owns Westlaw and a large tax and accounting franchise, with CoCounsel as the named AI product doing legal drafting and research. The structure is the same as RELX -- proprietary legal ground truth, an AI layer that sells the answer instead of the search -- on a somewhat narrower base. Delete the model and the business survives comfortably. It carries the same 3/3 lab-encroachment risk for the same reason, and the two names should be held as one position in thesis terms rather than as diversification, because they will be right or wrong together.",

"MDB": "MongoDB sells a document database, and Atlas Vector Search puts the embedding store next to the operational data rather than in a separate vector database. That matters architecturally because it removes a synchronisation problem for anyone building retrieval-augmented applications. Delete the model and MongoDB is still a serious database company, so centrality is 3 -- it is infrastructure UNDER the application layer rather than a member of it. It earns its place through the strongest practitioner evidence in the whole screen: 13 distinct operator-register terms on its engineering blog, more than double the next name, which is what writing by people who actually ship looks like versus marketing copy.",

"TEAM": "Atlassian runs Jira and Confluence, which between them hold an enormous corpus of how knowledge work actually gets done -- decisions, tickets, documents and the connections between them. Rovo is the named AI product built on that corpus, and the company has appointed a Head of AI and shipped an MCP server with over 1,000 GitHub stars, so the developer-facing commitment is real rather than asserted. Delete the model and Atlassian is a large, healthy software company, so centrality is only 2 -- this is a corpus-and-leadership name, not a model-native one. Lab-encroachment risk is 2/3, since much of what Rovo does is text over a corpus that a lab could plausibly reach through integrations.",

# ---------------------------------------------------------------- tier 3
"FICO": "Fair Isaac sells the FICO score, the standard consumer-credit risk measure in the United States, plus decisioning software. I included it and then downgraded it, and the reasoning is worth stating: the score is a regulated logistic scorecard, not modern machine learning, and that is not an accident. Under ECOA and Regulation B a lender must be able to explain every adverse decision, and that requirement effectively prohibits deploying an uninterpretable model -- the generalisable tell is that if regulation requires you to explain every decision, you cannot deploy an interesting model. It also directly contradicts Upstart, which sits at #9 on the argument that the regulated scorecard leaves money on the table; holding both at full conviction means being on both sides of one trade.",

"PL": "Planet Labs operates a constellation of imaging satellites that photograph the entire landmass of the earth daily, selling imagery and analytics to agriculture, defence and government customers. The daily global archive is a genuine and unreplicable data asset. I downgraded this one on inspection: much of the revenue is imagery ACCESS -- customers buying pixels and running their own analysis -- rather than inference sold as a product, so the AI is less load-bearing than the story suggests. Combined with a valuation around 35 times sales, the thesis requires the analytics mix to shift materially before the multiple is defensible.",

"MBLY": "Mobileye supplies ADAS and autonomous-driving systems to automakers, built on its EyeQ chips and a road-mapping dataset gathered from production vehicles. The technology is real -- computer vision and sensor fusion are the product, and ml_content scores a full 3. I marked it down on your competition point, and the mechanism matters: the thesis rested on an OEM-funded fleet compounding, and LTM revenue growth of 5.0% with gross margin at a series-low 42.9%, down 240bps year on year, says the design wins are not compounding. That is a centrality downgrade rather than a valuation call, because the asset the thesis rested on is eroding.",

"APTV": "Aptiv supplies ADAS perception systems, compute platforms and vehicle architecture to automakers. Sensor fusion genuinely is the product it sells -- combining camera, radar and lidar into a coherent picture of the road is the hard technical problem, and it does that work. The limiting factor is structural rather than technical: Aptiv is a supplier, not an owner. It does not own the fleet, the data or the customer relationship, so it captures a supplier's margin on someone else's autonomy programme and bears the OEM concentration and pricing pressure that comes with that position.",

"NP": "Neptune Flood underwrites residential and commercial flood insurance in the US, competing with the federally-run NFIP. The underwriting model IS the company: it prices flood risk at the individual-property level from elevation, hydrology and claims data, and quotes in seconds where the traditional process takes days. Delete the model and there is no underwriting capability and therefore no insurer. It clears the filing-language screen strongly, and the risk is the one every insurer carries -- a model that misprices tail risk is invisible until a bad year proves it.",

"OPEN": "Opendoor buys homes directly from sellers, holds them briefly and resells them, with an automated valuation model deciding what to bid. The AVM is genuinely central -- buying a house at the wrong price is the only way this business loses money -- and the model does appear to work, with gross margin improving from 7.2% to 9.7%. But the honest read is that this is a rates trade wearing an AI thesis: revenue is down 44% from peak, and the margin improvement came substantially from buying fewer houses rather than from pricing them better. A model that is right about prices cannot rescue a business whose cost of capital and volume both move against it.",

"SPGI": "S&P Global owns credit ratings, market indices and Capital IQ, which is one of the deepest proprietary financial corpora in existence. It has appointed a Chief AI Officer and topped the officer screen, and it is exposing data through agent-addressable surfaces. It carries a claims-exceed-traction flag: the filing language and executive appointments are well ahead of any observable practitioner adoption, with essentially zero GitHub traction. Delete the model and the ratings and index franchises are untouched -- these are among the best businesses in the world and they are not AI businesses, which is the accurate way to hold the name.",

"CLBT": "Cellebrite sells digital-forensics software to law enforcement, extracting and analysing data from seized phones and devices. The extraction step is engineering rather than AI -- getting data off a locked device is a security problem. The AI is in what comes after: triaging terabytes of messages, images and location data to surface what is relevant to an investigation, which is the labour actually being replaced and increasingly the part customers pay for. Delete the model and extraction still works but investigators drown in the output, so the model is becoming load-bearing without yet being the whole product.",

"SPOT": "Spotify streams music and podcasts, and personalisation has been core to its product for a decade -- Discover Weekly, and more recently the AI DJ, which uses a generative voice to program and narrate a personalised stream. This is the clearest example of your named-product test applied honestly. It ranks mid-list because of where the value lands: the AI improves retention and engagement, but it does not create a separately-priced revenue line, and the economics of the business are still set by label royalties. Delete the model and Spotify is a worse product that still sells the same subscription at the same price.",

"RBLX": "Roblox operates a user-generated gaming platform used heavily by minors, where machine learning does two distinct jobs. The first is safety -- moderating text, voice and 3D content at a scale no human team could cover -- which is not a growth feature but a licence to operate, since regulatory failure is an existential risk. The second is generative creation, letting users build assets and experiences from natural language, which lowers the barrier to supply on the platform. Delete the models and the platform cannot legally or practically function at its current scale, but the business is bookings from virtual currency, so centrality is 2.",

"CHRW": "C.H. Robinson is a freight broker, matching shippers with carriers, which is a business built on human brokers making phone calls. It is on the list because it is the clearest test case for AI substituting for labour in a non-technology industry: it has deployed agents to quote, tender and track freight automatically, and the result shows up in a publicly auditable number. Shipments per employee is the falsifiable metric -- if the agents work, that ratio rises persistently, and if it does not rise the story is not true. Delete the model and the brokerage still operates with more people at lower margin, so this is a cost-substitution thesis rather than a product thesis.",

# ---------------------------------------------------------------- below the discrimination floor
"ISRG": "Intuitive Surgical makes the da Vinci robotic surgical system, with a large installed base and a razor-and-blade instrument model. It owns what I believe is the best unconverted dataset in medicine: millions of hours of surgical video paired with synchronised instrument telemetry, so every frame is labelled with exactly what the surgeon's hands were doing. There is no meaningful AI revenue today, which is why it sits below the discrimination floor -- but it is the strongest candidate in that group to graduate, and the business is excellent regardless, with revenue up 18.5% and operating margin expanding to 33.6%. Own it for the robot; treat the corpus as a free option, and watch for a reimbursed AI product as the trigger.",

"SHOP": "Shopify provides e-commerce infrastructure to millions of merchants and sees the resulting transaction, catalogue and storefront data. It has an unusually AI-forward CEO, clears three separate filing screens and has appointed AI leadership, and it ships genuine AI features -- Sidekick for merchant assistance and generative product content. Delete the model and Shopify is entirely intact, which is why centrality is 2: the AI improves merchant retention rather than creating a priced product line. Notably, its engineering blog scored zero operator-register terms on a large feed, meaning the absence is a real finding rather than a sampling artifact.",

"FDS": "FactSet provides financial data and analytics to institutional investors, competing with Bloomberg and S&P. It is the name you raised yourself, and the screens recovered it independently: it clears all three EDGAR screens, has a Chief AI Officer, and is exposing its corpus through MCP so that agents can query it directly, which is the application-layer bet stated out loud. It carries a claims-exceed-traction flag that I have verified is a FALSE POSITIVE -- the MCP server is real, it is simply not on public GitHub, which shows the flag cannot distinguish absent traction from traction I have no instrument to see. Lab-encroachment risk is 2/3, since financial summarisation over licensable data is exactly what a frontier lab can ship.",

"FIG": "Figma makes collaborative interface-design software, and holds design files as structured data -- layers, constraints and components -- rather than flattened pixels. That structure is what makes generative design tractable, because a model can manipulate real objects instead of inferring them from an image, and it is why its MCP server has attracted over 1,900 GitHub stars. Delete the model and Figma is unaffected as a business. It sits below the floor because the AI is an accelerant on an already-dominant product rather than the product itself, and lab-encroachment risk is 2/3.",

"V": "Visa operates a global payment network and sees a transaction graph that is among the most valuable proprietary behavioural datasets in finance. It applies machine learning to fraud scoring on that graph and is building an agentic-commerce surface for AI agents that transact on a consumer's behalf, which is a genuinely interesting forward option. But delete every model and the network is completely untouched -- it clears payments exactly as before, which caps centrality at 2. This is an outstanding business that is not an AI business, and the classification below the floor says so explicitly rather than implying it is a weak AI name.",

"OUST": "Ouster makes lidar sensors and increasingly bundles perception software that turns the point cloud into detected objects. The perception layer is real machine learning and moves it up the value chain from pure components. The limitation is structural and it is why it sits in the supplier group: Ouster sells INTO other people's autonomy stacks, so it captures component economics on someone else's system and its fortunes track their build cycles rather than end-market adoption. At roughly $4.3bn it is also exposed to the consolidation that has repeatedly swept the lidar sector.",

"WLY": "John Wiley publishes academic and professional content and owns a deep scholarly corpus. It does something genuinely rare, and it is why you flagged it: it licenses that corpus to model developers and is one of only five 10-K filers in fourteen months to print the exact phrase 'AI revenue', which is a costly disclosure to make falsely. But size it honestly -- revenue is flat at +1.2% year on year, and the operating-margin improvement from 20.1% to 25.3% is cost reduction, not AI mix. The corpus licence is a real option and the disclosure is admirable; it is not yet moving the business, which is why it classifies as immaterial-to-P&L.",

"ESTC": "Elastic sells search and observability software built on Elasticsearch, with vector search making it retrieval infrastructure sitting underneath retrieval-augmented applications. The developer surface is real, with a 765-star MCP server and genuine practitioner traction. It sits below the floor for the same reason as MongoDB but with a weaker case: it is infrastructure UNDER the application layer rather than a member of it. It also just took a leadership-churn flag -- Chief Product Officer Ken Exner resigned in June 2026, disclosed in the same 8-K as a restructuring plan, which is a combination worth noting rather than reading as two separate events.",

"NU": "Nu Holdings is a Latin American digital bank serving over 100 million customers on an in-house core banking stack it built itself. Its AI claim is genuinely load-bearing in a way most banks' are not: it underwrites customers who have no credit-bureau file at all, using first-party behavioural data from the app, which means in a thin-file market it effectively IS the bureau. Delete the model and it cannot underwrite that population, so the capability is real. It classifies as thesis-adjacent rather than a member because the investment case is a fintech and emerging-markets banking story in which the model is one input; operating expense per active customer is the metric that would falsify or confirm the efficiency claim.",
}
